### ISSUE TITLE
orix 0.6.0

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#145]
UPDATED: New list, with a planned Mid-May release:

0.6.0
------

- [ ] Overwritten operator clean up; see #139 and #140
- [x] Bugfix for #159 (io) 
- [x] Bugfix for #160 (io)
- [x] Bugfix for #167 
- [x] Issue #175 which is addressed in #193 (sampling efficiency)
- [ ] Black the whole code 

Pushed to 0.7.0
---------------------

- Crude colouring scheme for CrystalMap, which is talked about in both #126 and #122 

Previous Text in this Issue
-----------------------------------

After conversations this week, a plan for orix 0.6.0 has solidified.

We're expecting solutions and implementation for:

- [x] Exporting CrystalMap to ang formats (#127) with (#144)
- [x] Documentation pages clean up, see PR #135
- [x] Stereographic projection (#146)

I think the main discussion here is about the final bullet point. Correct me if I am mistaken, but I think @din14970 was expecting to put a streographic projection (in a projections module?) and a (rough) IPZ plotter somewhere. Meanwhile 
@hakonanes was planning RGB colouring (and a general framework for such colouring schemes).

and then this means that:

@din14970 can work on stereographic projects without any new code going in. However we probably want to drop the IPZ plotting into the framework @hakonanes is planning. Am I missing something here?

**Comment by hakonanes** [comment]
This sounds good! I'm ready to review any coming PR.

Regarding the projections module, I plan for us to put [spherical](https://github.com/pyxem/kikuchipy/blob/b31781dc3c75cc75cf0dd9eb43fb61bee8894748/kikuchipy/projections/spherical_projection.py#L30), Gnomonic, and the modified Lambert projections from kikuchipy into that module. The setup is based on MTEX' spherical projection, with a projection and possibly an inverse projection. It takes vector3d or numpy arrays of arbitrary shapes with the last axis of length 3 (x, y, z). I hope we can adopt this setup (or perhaps something even better) for the projections module in orix. And reserve all plotting stuff for the `plot` module, since the projections won't only be used for plotting!

**Comment by hakonanes** [comment]
I can add a `orix.data` module with a few small example datasets, if it's desirable and if you can give me some suggestions?

For kikuchipy, I find it simpler to write documentation and test new functionality when having some example datasets available in our [`data module`](https://kikuchipy.org/en/latest/reference.html#data).

This would then be importable like (perhaps with a shorter name)

```python
>>> from orix import data as orix_data
>>> xmap = orix_data.small_super_duplex_stainless_steel()
>>> xmap
Phase  Orientations                 Name  Space group  Point group  Proper point group       Color
    1  5657 (48.4%)  austenite/austenite         None          432                 432    tab:blue
    2  6043 (51.6%)      ferrite/ferrite         None          432                 432  tab:orange
Properties: iq, dp
Scan unit: um
```

**Comment by pc494** [comment]
I think the current consensus is to leave the orientation colouring to a 0.7.0 release & instead push on and try and release a 0.6.0 as we now have a good batch of features that have not yet shipped. I think the main things that are left are #139 and #140 (again) plus the newly noticed #175.

**Comment by hakonanes** [comment]
I think #167 should be added as well, I will have a look at this in the next couple of days.

**Comment by hakonanes** [comment]
I'm also nearly done with fixing #159 and #160.

**Comment by pc494** [comment]
Ah cool, I think mentally I had marked them as "safe to do as patch" but it would be great to have them for `0.6.0`. Shall we target mid-May for a release?

**Comment by hakonanes** [comment]
Agree, they are safe to do as patches. We could add them to 0.6.1, will see how easy they are to fix. The issues you mentioned are more important!

**Comment by pc494** [comment]
Also, @hakonanes I think we should put `.ipynb` back in the `.gitignore`, if one changes the docs it's not that hard to find the `-f` command and it clogs up the commit list as it is because the unique IDs sometimes get changed.

**Comment by hakonanes** [comment]
Yeah, definitely, I will have a look around the internet and see if there is a simple solution.

**Comment by hakonanes** [comment]
@pc494, I can set up this release if you don't have time.

**Comment by pc494** [comment]
Update on this: the work in #193 is proving a bit more substantial than previous thought. Given that #175 isn't really fixed until that's merged I'm holding off releasing for now. I'm optimistic about the chance I can finish it in the next couple of days. But if not our release may be delayed. Anyone with strong feelings about timings, now would be a good time to shout.

**Comment by hakonanes** [comment]
The work you're doing in #193 is important, so I'm totally OK with a delay.

**Comment by pc494** [comment]
When #193 goes in I'm going to tidy up and get a release out.

**Comment by hakonanes** [comment]
Sounds good!

**Comment by hakonanes** [comment]
Released!
