### ISSUE TITLE
Version 0.7 is coming

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#224]
After the discussion in #221 it's been decided to get 0.7 released soon (w/c September 6th ideally). There are very few outstanding items, but they are:

- [x]  #221 itself, which adds new functionality
- [x] #223 which will close #215 
- [x] #222 which will close #216

**Comment by pc494** [comment]
@hakonanes how do you feel about pushing #208 to a later release? If we do that I think this is now good to go?

**Comment by hakonanes** [comment]
Yeah, go ahead! I can do #208 afterwards.

**Comment by pc494** [comment]
Great, planning to do this today then :)

**Comment by hakonanes** [comment]
... aand it's here!
