### ISSUE TITLE
orix-0.4.0

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/orix#84]
Since orix-0.3.0 is now released it seems a good time to write a list of functionality on the road map for 0.4.0.

The following will be part of orix-0.4.0:

- [x] Porting and improving the creation of orientation space grids from diffsims to orix #71 
~Adding stereographic projection #62~
- [x] Implementation of to_matrix() etc. methods in Rotation #79 
- [x] Developer improvements (#88)
- [x] Add space group to `Phase` class (#104)

Does anyone want anything else on the list? @hakonanes @pc494

**Comment by pc494** [comment]
That looks good to me.

**Comment by hakonanes** [comment]
Have you guys considered creating a `Miller` class, inheriting from `Vector3d`, for handling directions with respect to crystallographic axes, or do you think this is unnecessary? I'm fidling with creating plane/direction families for a given unit cell, and it would be nice to have: a `Miller.equivalent()` method to compute the equivalent indices of planes/directions, a `Miller.length()` for computing the length of a direction in direct or reciprocal space, etc. These computations should be made with the direct/reciprocal metric tensors available in `diffpy.structure.Structure.lattice.metrics`/`diffpy.structure.Structure.lattice.reciprocal().metrics`.

I cannot think of anything more at the moment.

**Comment by hakonanes** [comment]
I see there are some stuff in `diffsims.utils.sim_utils` which could be relevant.

**Comment by dnjohnstone** [comment]
I think that's something that would be useful - I think we've not gone there so far primarily because a part of me thinks it shouldn't really be in orix though and should rather be in diffpy.structure or whatever crystal structure package we use.

However, we essentially need this for some of the orientation space grid options that are currently in diffsims so maybe the weight balance of effort to reward is tipping.

I do think we want to think quite hard about how we want to approach crystal geometry in general though i.e. do we want to reach out to the diffpy.structure people to try and work with them to extend that. I feel like this the kind of situation that has led to the already bad fragmentation of crystallographic python libraries.

pymatgen had some of this stuff in and I'm sure it's in cctbx somewhere but we steered away from both of those because they're behemoths.

**Comment by dnjohnstone** [comment]
Is there anything else we want for 0.4.0? If not I'll set the "due date" to be the end of August?

**Comment by hakonanes** [comment]
Considering I might not at the moment need the space group to get the desired symmetry operations from the `Phase` object (https://github.com/pyxem/orix/issues/87#issuecomment-671307799), I cannot of anything else not on the list that I need from orix right now.

**Comment by hakonanes** [comment]
I'm going back and forth about adding the space group to the `Phase` object... I've finally decided to leave it for the future.

**Comment by hakonanes** [comment]
> I think that's something that would be useful - I think we've not gone there so far primarily because a part of me thinks it shouldn't really be in orix though and should rather be in diffpy.structure or whatever crystal structure package we use.
> 
> However, we essentially need this for some of the orientation space grid options that are currently in diffsims so maybe the balance of effort to reward is tipping.
> 
> I do think we want to think quite hard about how we want to approach crystal geometry in general though i.e. do we want to reach out to the diffpy.structure people to try and work with them to extend that. I feel like this the kind of situation that has led to the already bad fragmentation of crystallographic python libraries and maybe we have an opportunity to pick a horse and pull together rather than splitting again.
> 
> pymatgen had some of this stuff in and I'm sure it's in cctbx somewhere but we steered away from both of those because they're behemoths.
> 
> Would be interested to hear what others think about this?

I've thought a bit more about a `Miller` class. To construct a `Miller` object, we need some indices (either hkl, hkil, uvw or uvtw) and symmetry operations of the crystal lattice. The former we can (at least for hkl and uvw) represent by the `orix.vector.Vector3d` class, while the latter we can get from `orix.symmetry.Symmetry` objects. I'm not sure how often we would need lattice parameters for any `Miller` class methods? Considering this, I think the class should be implemented in `orix`. Otherwise the other package to implement it in would need a class equivalent to `Vector3d`?

**Comment by hakonanes** [comment]
> Things have moved pretty quickly on this, and once #104 is agreed and in we will have almost everything we originally expected for this release. I realise since then we've put #95 on the list, and I expect we will deal with the (currently poorly specified) #76 but is that all?

Yes, I have nothing more at the moment.

**Comment by dnjohnstone** [comment]
> Things have moved pretty quickly on this, and once #104 is agreed and in we will have almost everything we originally expected for this release. I realise since then we've put #95 on the list, and I expect we will deal with the (currently poorly specified) #76 but is that all?

Yes, I think that's all - I've struck off #62 for now for the reasons set out in a comment on that PR.

**Comment by dnjohnstone** [comment]
Are we good for a 0.4.0 release or do the additional PRs mentioned in #104 want to be added to this?

**Comment by pc494** [comment]
I think we at least want the hdf5 PR in

**Comment by hakonanes** [comment]
> I think we at least want the hdf5 PR in

See #106.

**Comment by pc494** [comment]
In the short term I think we should deal with the matplotlib axes ratio in notebooks, so I'm going to tagged a `0.4.0.rc1` this evening, with the hope to have a `0.4.0` release tomorrow

**Comment by hakonanes** [comment]
Running

```bash
$ conda create -n orix-rc python=3.8
$ pip install orix[dev]==0.4.0rc1
$ pytest --pyargs orix
```

went smootly. I guess you decide whether an rc is successful by looking at the CI, @pc494?

**Comment by pc494** [comment]
It's mainly about getting the settings for the conda build correct when dependencies are at different level of complete in pypi/conda - but the feedstock hasn't pinged me yet

**Comment by hakonanes** [comment]
Ah okay, guess the highest potential for failure lies in the conda build.
